### ISSUE TITLE
Loading datetime field extension

### ISSUE THREAD

**Issue by chromjak** [ReduxFramework/redux-extensions#148]
Hi, just purchased the Datetime extension but can seam to make it load. I am loading the field extension before Redux and set the 'opt_name' in extension loader but still no luck. 

The following is a simplified example test in 2014 theme in functions.php added: 
```
require get_template_directory() . '/extension_datetime.php';
require get_template_directory() . '/options.php';
```

extension_datetime.php located in theme root:
```
if (!class_exists('ReduxFramework_extension_datetime')) {

    /**
     * Main ReduxFramework icon_select extension class
     *
     * @since 3.1.6
     */
    class ReduxFramework_extension_datetime {

        static $version = "1.0.3";

        // Protected vars
        protected $parent;
        public $extension_url;
        public $extension_dir;
        public static $theInstance;

        /**
         * Class Constructor. Defines the args for the extions class
         *
         * @since 1.0.0
         * @access public
         * @param array $sections Panel sections.
         * @param array $args Class constructor arguments.
         * @param array $extra_tabs Extra panel tabs.
         * @return void
         */
        public function __construct($parent) {
            $this->parent = $parent;
            if (empty($this->extension_dir)) {
                $this->extension_dir = trailingslashit(str_replace('\\', '/', dirname(__FILE__)));
            }
            $this->field_name = 'datetime';

            self::$theInstance = $this;

            add_filter('redux/xxx/field/class/' . $this->field_name, array(&$this, 'overload_field_path')); // Adds the local field
        }

        static public function getInstance() {
            return self::$theInstance;
        }

        // Forces the use of the embeded field path vs what the core typically would use
        public function overload_field_path($field) {
            return dirname(__FILE__) . '/' . $this->field_name . '/field_' . $this->field_name . '.php';
        }

    }
} 
```

in option.php opt_name set ('opt_name' => 'xxx') and field declared:
```
                        array (
                            'id'            => 'opt-date-time',
                            'type'          => 'datetime',
                            'title'         => 'Date/Time Picker',
                            'subtitle'      => 'Date/Time Picker extension',
                            'split'         => false,
                            'separator'     => ' @ ',
                         
                            // Optional timezone list
                            'timezone-list' => array(
                                array('value' => -300, 'label' => 'Eastern'),
                                array('value' => -360, 'label' => 'Central'),
                                array('value' => -420, 'label' => 'Moutain'),
                                array('value' => -480, 'label' => 'Pacific')
                            ),
                            'timezone'      => '-300',
                         
                            // Optional Min/Max hour values
                            'hour-min'      => 8,
                            'hour-max'      => 16,
                         
                            // Optional Min/Max minute values
                            'minute-min'    => 20,
                            'minute-max'    => 40,
                         
                            'date-min'      => 0,
                            'date-max'      => 30,
                        ),
```

The datetime extension folder located in theme root.

Help would be appreciated, thank you. Ivan

**Comment by kprovance** [comment]
That's now how you'r supposed to load extensions.  Instructions were provided on the docs page:  http://docs.reduxframework.com/core/advanced/loading-extensions/

**Comment by chromjak** [comment]
Thank you for that answer, I have spend enough time going through all that, loading extension and loading a custom field seam to be done from different folders. Where can I get a refund?

**Comment by kprovance** [comment]
Sorry, but our policy is quite clear on this:  Once you have the code, no refunds are given.  We have no assurances you won;t still use it at a later time.  All sales are final.

**Comment by chromjak** [comment]
I understand your time is precious but so is ours. From five past purchases two had major issues on your end making the unusable, that were later fixed but wasted lot of our time, one couldnt be downloaded while hunting down any support and you can't spare a minute. You have the best free product out there but premium far from it.

**Comment by kprovance** [comment]
You're dinging me because you didn't set up the extension properly?  Hardly seems fair.  Instructions were provided, and an EXTENSIVE docs page as well.  What is it you want me to do?  Download your theme and set it all up for you?  Basic PHP coding falls under premium support, but if it'll make you happy, I'll do it this ONE time, gratis.  info@reduxframework.com

**Comment by kprovance** [comment]
I looked at what you sent me.  Simply put, you can't do it the way you have it set up.  You can't take apart the structure of the datetime folder and move stuff around.  You MUST use our loader.

So, in your theme folder, you have to do something like this  `theme/redux/extension/datetime`

The datetime folder as I authored it, not the one you've changed.

In `theme/redux` you have to add the loader.php (https://github.com/ReduxFramework/redux-extensions-loader/blob/master/loader.php) making sure to change the function name and add your opt_name where indicated.

Finally, in your functions.php, take out the include for the date time and change it to the loader.php

Done.

**Comment by dovy** [comment]
@chromjak, just because you got other extensions to load in a certain way outside of what we suggest, doesn't mean it was the correct method.

We created the extension loader to ensure complete compatability between extensions. If you go modifying our structure, and bypassing the loader how can we be held responsible for it "not working?"

Please just try what @kprovance send you and you'll see it works as we say it does.

I KNOW there's a learning curve in Redux. It requires some pretty solid understanding of PHP and WordPress hooks/filters. 

In the future, might I suggest, you use the Redux Builder http://build.reduxframework.com and it will provide for you a fully functioning admin folder. From there you'll only need to drag and drop files.

We're doing the best we can. We can't code for you, we can only fix our bugs. Bugs induced by our user that do not follow our documentation are errors on your end, not ours. We can't be held responsible or support freely such actions or we'd be doing this all day.

Know that each of your extensions work. As soon as you figure out HOW to get them to work it will make perfect sense.

Thank you for being patient. Good luck!
