### ISSUE TITLE
Notice bug

### ISSUE THREAD

**Issue by louisriom** [ReduxFramework/redux-extensions#149]
Hi, 

Since the update, the notice dosn't disapear, which hide my admin panel.. (please see in attachement)

Can you help me ? 

Thank you

**Comment by kprovance** [comment]
NO attachment.  NO idea what' you're talking about.  #1975

**Comment by louisriom** [comment]
Talking about the notice displayed just after an update. 

Can you see the attachment ? 


Date: Wed, 4 Feb 2015 06:17:23 -0800

**Comment by kprovance** [comment]
No, but again PLEASE READ #1975.  NO version info, no mention of which extension you are using.  No nothing.  I can;t give you support without this information.

**Comment by kprovance** [comment]
Oh, you can;t read that post, wrong git.  Here:

## Posting Guidelines for issues and questions ##
When using our Issue Tracker, you may ask questions where you may be a bit lost or need help understanding the documentation. If, however, you find a bug we require you to read and provide the information contained in our [Contributing Guidelines](https://github.com/ReduxFramework/redux-framework/blob/master/CONTRIBUTING.md). If you do not provide this information, we will request it before we can support you.

If you are stuck in some of your own code, or need help with PHP and anything else not Redux specific, we request you purchase some [Premium Support](http://reduxframework.com/extension/premium-support/) and we will be happy to assist you. If we feel the issue is outside of our scope we will suggest you to purchase some [Premium Support](http://reduxframework.com/extension/premium-support/) in order for us to serve you.

**Comment by louisriom** [comment]
I'm using that : 

Redux Framework Version 3.4.2.2
Wordpress 4.1
MedicalPress : 1.0

Date: Wed, 4 Feb 2015 14:18:21 -0800

**Comment by dovy** [comment]
Are you a user or theme developer?

**Comment by louisriom** [comment]
I'm a user

Date: Wed, 4 Feb 2015 16:13:01 -0800

**Comment by kprovance** [comment]
Then you need to contact the theme developer and report the issue to him.  If he has an issue, then he can report it to us, probably with the information we needed.

**Comment by dovy** [comment]
Also you can install this plugin from the WordPress plugin browser and the notices will go away:

https://wordpress.org/plugins/redux-developer-mode-disabler/

But please do notify the creator of your theme. Best of luck!
