### ISSUE TITLE
Problem Widget Areas extension

### ISSUE THREAD

**Issue by nicolas92** [reduxframework/redux-extensions#200]
Hello, there is a problem with the widget areas extension, when I update my theme, all of the sidebars create widgets with the extension does not automatically put in the sidebars, they are in inactive sidebar, is it possible to solve this problem?
Thank you a lot.

**Comment by dovy** [comment]
@nicolas92 on every update? Not sure how that could be the case... How are you running your update?

P.S. Sorry for the lack of response. Was away.

**Comment by nicolas92** [comment]
Hello, no problem :)
Yes, on every update, I erase the theme via ftp, then I install the new version using the wordpress admin and each time, the widgets of customs sidebars created with the extension are in "Inactive Sidebars".

**Comment by kprovance** [comment]
I think this is because, when a theme is activated it registered it's own sidebars.  Since the theme does not know what sidebars were created with the ext, it doesn't register them.  We'd have to recode the ext to remember what sidebars it registered per theme, and then register them on activation, I think.

**Comment by dovy** [comment]
Actually, this is by design ala WordPress.

If you ever deactivate a theme every, and then re-activate, all the old widgets are removed and placed in inactive. This is to ensure that there is not cross-over between themes.

If you don't want to experience this, don't deactivate the theme at all. Just ftp, switch the folders, and run. Everything will stay as expected.

This is a WordPress design choice, not a bug in our extension.  ;)

**Comment by nicolas92** [comment]
Oh, okay, thank you very much, at least now I know :)
I thought it was a bug, thank you :)

**Comment by dovy** [comment]
You are so welcome. Best of luck to you.

Oh, and if you have the means, contribute to the customizer project! https://ideas.reduxframework.com/campaigns/complete-customizer-integration/

**Comment by nicolas92** [comment]
I'll do it in a short time :)
