### ISSUE TITLE
Metaboxes - Required field doesn't work on  WP4.2.4

### ISSUE THREAD

**Issue by aonzzung** [reduxframework/redux-extensions#222]
WP4.2.4
Metaboxes 1.3.0
Redux Framework 3.5.6.2

---------------------------

On Metaboxes for a page, I created a button_set to have A/B options. When I select one of A/B options, all fields (depending on a selected option of this button_set) always show regardless of the selected button_set option (not recognise 'required' field).

Anyways, 'required' field on Redux theme options works as usual.

Thanks for taking a look

**Comment by kprovance** [comment]
That version of Metaboxes has required issues.  An update is in the works.  No ETA.

**Comment by aonzzung** [comment]
I checked it and saw that the latest version is 1.3.0, isn't it ?
![screen shot 2558-08-16 at 4 13 25 pm](https://cloud.githubusercontent.com/assets/3109162/9292690/ff26afaa-4431-11e5-9dbe-3829823764d9.png)

NOTE: I also re-download and try it again and it still doesn't work.

**Comment by aonzzung** [comment]
Ah, I think I missed reading  "It's in the work". I'll wait for the fix.

**Comment by monstertheme** [comment]
No estimated time. I have a feeling it's going to be a couple of months though.

**Comment by aonzzung** [comment]
@monstertheme lol thanks for the meaning. I have an inner feeling that they will make it sooner :cry:

**Comment by kprovance** [comment]
ETA = 'Estimated time arrival', which, yes, is the American way of saying 'I have NO idea when it'll be finished.'

I don't believe, however, it will be counted in terms of months.  Dovy has been making tweaks to it regularly.  It's just that sometimes tweaks required more tweaks.  The required thing being one of theme, and some serious CSS restyling, which I believe is worth the wait, because it's a nice improvement.  :)

**Comment by aonzzung** [comment]
@kprovance Thanks for clarification.

During waiting time, I think I should downgrade to lower version.
However, I've tried using 1.2.9 and the required field still doesn't work.

Do you have other archived versions?

Thanks

**Comment by kprovance** [comment]
No, sorry.  Email me: kevin@reduxframework.com.  I have an unofficial 1.3.4 version I've been using for a bit in which required works.  You are welcome to use it with the understanding that it's unsupported until Dovy makes an official release.  The reason being updates have been made since the internal version we've been using to test things and I can;t push code changes to it.  :)

**Comment by aonzzung** [comment]
Thanks @kprovance I already sent you an email. :+1:

**Comment by aonzzung** [comment]
Hi Guys @kprovance @monstertheme 

After spending hours of experiment, I found a temporary fix for this.

**Solution**
Which options we want to have on metaboxes, we have to add it to admin options too (even tough we don't want it to be on admin options ~ you may have to use js to hide it). 

If the options are only on metaboxes, required fields will never work.

:sweat:

**Comment by dovy** [comment]
Yea, the issue is the file type is not added to the Redux object. I have a solution, but it breaks other things. This is extremely complex code. I'm doing my best.

A sure fire solution for now, is just to add the "hide" text to the class arg for a field you also place within your options panel.  ;)

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
