### ISSUE TITLE
Metaboxes - Ajax Reset

### ISSUE THREAD

**Issue by pootato** [reduxframework/redux-extensions#227]
Hello,

I was curious if it was possible to add an Ajax reset button to each Metabox?

Currently, the user would have to delete the page in order to reset to default values.

I searched and found https://github.com/reduxframework/redux-extensions/issues/102, but the post is a year old and I'm not sure it's the best solution with the new API.

Thanks!

**Comment by kprovance** [comment]
We've reached a point here where new features will require financial backing from the community.  Since devs do not like to donate to us - when they're making bank thanks to our work - we've become unmotivated to do anymore, for little to nothing.  It's not that I dislike the idea, but I think it would require more than a few hours work for little to no return on our investment.  That said, feel free to submit the idea at ideas.reduxframework.com.  If devs want to back it, it could become a reality.

**Comment by pootato** [comment]
Talk about jumping the gun without reading the post.

I'm not asking for a new feature, I'm asking if the post I linked is still a viable solution.

**Comment by kprovance** [comment]
I don't know.  Why not just try it and find out?

**Comment by pootato** [comment]
I'm sure $7000 is plenty to at least assist users who purchased extensions with updated releases.

**Comment by dovy** [comment]
Sorry @pootato, we're a little gun shy about adding new things. Both @kprovance and I are a bit strapped right now beyond belief. hah.

**Comment by dovy** [comment]
Yes, that paid for 2 months of dev time while I worked on it. No need to be cross. Imagine how we feel when we see this: https://reduxframework.com/showcase/envato/, which hasn't had new products added for months.

Remember my friend, it's all relative.
