### ISSUE TITLE
Pre-Sales Question (Repeater / Premium Support)

### ISSUE THREAD

**Issue by gsmarketing** [reduxframework/redux-extensions#245]
I don't know if this is the right place to put this, I don't see any other area to contact the Redux team about pre-sales and the documentation (while very in-depth) is succinct about what it does and less what it can do. This may be a Pre-sales Question for Both Repeater and Premium Support. I am happy to pay the good developers of this system if it can fit my needs.

Affecting Users from Redux Options:
- In my plugin I have a feature where the admin can require users confirm their account before being able to login. In certain cases where this fails, my pre-redux system uses an ajax powered field that you lookup a username and you can click to edit them which opens a popup to manually confirm them. I am assuming that with the Custom Extension Boilerplate we could rebuild this to work in Redux to function the same, is that correct?

User Meta from Repeater Field: (MOST CRITICAL)
- In my pre-redux system we are creating a new table in WP (sacrilege) to let the admin define custom fields of a sort. Each one gets a unique ID in the table that we use to associate to user_meta if a user saves data to one of the fields. So we know user_id: 255 has saved data associated to custom_table_item_id: 2. And we can call that through the site where its needed. We also have shortcode that allows the admin to choose to show where on the site which special custom field.

I would like to leverage the same feature where the admin can create as many of these special fields via the repeater (I'm assuming it works similarly to Advanced Custom Fields repeater). An Image, a Name, a Link and a User Value.

The question is, can I leverage this as it relates to a user. Where the admin can call a specific entry like: [special_custom_field id='1'] and I can retrieve the first entry of the repeater field. And more importantly, the "User Value" field will allow me to save to user_meta the data they enter to this field as opposed to a global wp_option value?

**Comment by ericwallen** [comment]
I would not buy. These guys stole $200 of my money and refuse to support their product. Going to post a new thread today but the guy who runs it (kevin) is a major punk. Trust me you will want to work with someone other than these jokers.

**Comment by dovy** [comment]
Hello @gsmarketing. I am sorry about the comment you just received. We attempted to support that user, but he neglected to use the code we sent him. It's sad it turned out as it did.  :(

Your first question is a big yes. It's extremely easy to make your own fields and extend Redux. It will take a little bit of exploration, but once you get it you'll find it's a snap to develop your own fields.

Your second question is a bit more tricky, but entirely doable. What you would have to do is hook into the save function and modify where those "user only" fields go. The repeater field could easily do the data (you could even nest it all under a variable name), but to save it as user meta will take a bit more effort. Not horrible, but a bit. 

I hope that answers your questions!  :)
