### ISSUE TITLE
How to add some color schemes using the code to be a part of the WP theme?

### ISSUE THREAD

**Issue by danielwebguy** [reduxframework/redux-extensions#250]
Hi
We are using the color scheme extension and we need to create some color schemes in the code. We don't find the way yo do it.
On the documentation page it is written that the best way is to add it on the user interface but we want to launch the theme with some options for the user to begin with.
How should we do it?
Please advice,
Daniel

**Comment by kprovance** [comment]
I don't understand the question.  The documentation page shows exactly how to create a color scheme page.  Naturally, you will need to match up the color black with whatever CSS you wish to assign to it (make sure the 'output' argument is set to true, so the values are outputted on the front end.  You may also set default colors, as per the docs page.  Therre's no other place to select those colors, but via the Redux option panel.  Again, I'm not sure what it is you are asking.  I am unable to write any code for you and I do not know how you intend to design your site/theme.

**Comment by danielwebguy** [comment]
Hi Kevin,
I thank you for you answer.
we don't need to write code for us ofcourse.

on your documentation it is written like so:
--------------
Adding Schemes

The easiest way to create a new scheme layout is to make any desired color changes to the default scheme, provide a new scheme name in the Name text box, then click Add. This will commit the new scheme to the database without affecting the color selection in the default scheme. Please bear in mind, even though the new scheme is selected in the drop down selector, it will not be applied to the theme until Save Changes is clicked.
--------------

So is it possible to add scheme on the code? not on the UI?
we should be able to add multiple color schemes by code so users can choose from them when they install our theme.

Thanks,
Daniel

**Comment by kprovance** [comment]
At this time, no.  Only the default scheme can be set programmatically.  There might be ways to preinstall a saved JSON export of other schemes, but they would be complex, and not covered under the scope of support.

**Comment by danielwebguy** [comment]
I see.
Actually I am a bit surprised. 
Color Scheme idea is that there might be some....
do you have a read map to add it? if you have will it be soon?
thanks.

**Comment by kprovance** [comment]
When I wrote it, it was so that the user could come up with their own.  Yes, it's a cool idea to be able to add several at once, and if you create some and export the JSON file, it is possible to preinstall them by dropping it in the upload/redux/color-schemes folder (the extension will capture it at load, install the data in the database and delete the JSON file).  It's not a supported feature.  It was meant to convert the old data file from v.1 to the v.2 database.  It's merely a happy side effect that one can drop an export file in there and the info will transfer (it will wipe out existing data tho).

At this point, unless our end users begin to support us with donations, or begin purchasing enough extensions to make any kind of sustainable income, further development isn't in the immediate future.  I can count on one, maybe two hands the number of folks who have purchased this extension over the last two years, which is to say the return on all that work was technically considered a failure, and thus my lack of interest in further development on any extension.

I wish it were different.  I really do.

**Comment by danielwebguy** [comment]
You know, 
I myself, bought already two extensions, and donate 200$ for the customizer. 
I was under the impression that this framework is going wonderfull and I can count on it.
As I already told you a few weeks ago, it is very scary that I develop a complete package (theme & number of plugins) using your frame work, and now each time I ask a question a part of the answer that you are no longer developing it.
I can try to understand your side but it makes me worry.

sayiing that I will put a different question on a new thread.
Thanks,

**Comment by kprovance** [comment]
Redux isn't going anywhere.  It's still being supported, as are the extensions.  What I said was there probably won't be any new development until devs finally figure out we can't work for free, forever.  Both Dovy and I have to make ends meets.  We have families to feed and bills to pay.  Jobs that support that get top priority (and why I answered your post the same day).  Redux isn't paying for anything (well, not for me, anyway), so it had a lower priority.   

Of course, I will continue to support my extensions and fix issues.  Chances are I won;t be adding anything new to them.  Adding multiple preinstalled schemes via arrays would take a rewrite of the core plugin.  Lots of work, no return.  If you are a theme developer, you should understand that.  Would you keep reinvesting in your project if no one was buying it?  or if people were using it for free?

If those buzzards at ThemeForest would stop jerking me around over this review process and I had a reasonable cash flow, I might be inclined to do more free stuff for Redux.  Blame them.  ;-)
