### ISSUE TITLE
404 Page layout

### ISSUE THREAD

**Issue by linkinhas** [reduxframework/redux-extensions#253]
Hello guys , 
I'm working with a wordpress template that using redux framwork, the problem is i hided wordpress with wp hide plugin & i have page layout doesnt work anymore redux path are the only paths that the plugin couldnt change see screenshot   : http://hpics.li/c795ade
Page layout issue : http://hpics.li/79e3a56
i just want to know where can i change the path in order to make my page layout works .

Thank you

**Comment by kprovance** [comment]
This is not a Redux issue.  if another plugin (one that obfuscates wordpress itself) is changing the way paths within wordpress are outputted, then all bets are off.  Maybe it's an ABSPATH issue, I don't know.  Either way, it's not covered under the scope of our support.  We'd need a subscription for premium support for me to take a closer look...but even then, I couldn't guarantee a solution, because another plugin is changing the way wordpress operates in ways it was never intended.

**Comment by linkinhas** [comment]
Thank you for your quick answer , i dont have choice i'll give up to hide wordpress :)
