### ISSUE TITLE
Ad Remover

### ISSUE THREAD

**Issue by liquidbook** [reduxframework/redux-extensions#286]
I purchased the Ad Remover extension, but it does not seem to be working. I placed the extension inside redux-extensions > extensions. The extension-init seems to imply that extension will auto-load. I also tried changing the order option-init and extension-init, but no change. I get no red flags in the Redux status page. Redux is running as an embed to the custom theme. Any suggestions?

redux version = 3.6.1.3 
redux Ad Remover = 1.0
wp version =  4.6

running on a localhost (MAMP)

**Comment by kprovance** [comment]
It's just not loading because the config is incorrect someplace.  Are you using the Redux  setExtensions API, or the old loader?  Seeing your code would be very helpful here.

**Comment by kprovance** [comment]
I would also put the extension someplace else, outside of the core.  For example, if you have theme/admin/ReduxCore, the put it someplace like theme/admin/extensions.  Then in your config, use Redux::setExtensions ($opt_name, dir_to_ext_folder)  (Please replace both parameters with your specific data.  See https://docs.reduxframework.com/core/redux-api/

**Comment by liquidbook** [comment]
Hey Kevin,

Thanks for the fast reply. There is not config.php file in the redux-extensions (or in the configs), should there be a config file.
[options-init.php.zip](https://github.com/reduxframework/redux-extensions/files/457619/options-init.php.zip)

Happy to show code - but sure what you want to see.

**Comment by liquidbook** [comment]
I'm still being clueless. I tried adding this to my options-init.php:
```
	$ext_path = dirname( __FILE__ ) . '/redux-extensions/extensions/';
	Redux::setExtensions($opt_name, $ext_path);
```
no luck (and the options-init.php sets the $opt_name and the path should be correct for my system)

I shouldn't actually need the suggested code since the current version of redux seems to be written to load the extension if they are in the extension folder. The admin-init.php calls extensions-init which has:

 ```
// All extensions placed within the extensions directory will be auto-loaded for your Redux instance.    
Redux::setExtensions( 'liquidbook', dirname( __FILE__ ) . '/extensions/' );

    if ( file_exists( dirname( __FILE__ ) . '/configs/' ) ) {
        $files = glob( dirname( __FILE__ ) . '/configs/*.php' );
        if ( ! empty( $files ) ) {
            foreach ( $files as $file ) {
                include $file;
            }
        }
    }
```

**Comment by kprovance** [comment]
If you are embedding, do not use dirname, TF will ding you for it.  I don;t know if that will even work because I have no idea how your theme is laid out.  dirname with file pulls the dir from the location of the file from which it's called, so I don't even know if that path is correct.  Better to use WP API for that where possible. You're on a local install and I can;t login to see what you are doing wrong.  Your options-init is your config file.  The setExtensions API goes at the bottom (That's how I use it in my theme).  I don't know what the glob code is for.

$ext_dir = get_template_directory()  . '/admin/extentions/'
Redux::setExtensions( 'my_theme_options', $ext_dir);

That's it.  That's all one needs to do.

I guess I should say - coz I've seen people do it - the contents of the ad_remove folder must go into your extensions folder as is.  I've seen folks try to move files around and it work work.

**Comment by kprovance** [comment]
Going to close this since I've not heard back.
