### ISSUE TITLE
WP_Error as array in class.p.php

### ISSUE THREAD

**Issue by swapnilshetes** [reduxframework/redux-extensions#287]
PHP Fatal error:  Cannot use object of type WP_Error as array in  inc\admin\redux-framework\ReduxCore\inc\class.p.php on line 247

I am using redux framwork in WordPress.

I have track the issue in log. I got the above error.
You need to add try and catch in this. 
Please check and let me know the solution or proper explanation on this.

**Comment by kprovance** [comment]
I'm not sure why you posted this in the extensions tracker.  Is this in conjunction with a Redux extension?  If not, please post the issue here (https://github.com/reduxframework/redux-framework/issues), but PLEASE, read this first and make sure you provide the necessary details (https://github.com/reduxframework/redux-framework/blob/master/README.md)
