### ISSUE TITLE
JS Button: How to disable the Button / JS Function?

### ISSUE THREAD

**Issue by Stefan39** [reduxframework/redux-extensions#304]
How can i disabled the click on the JS Button?

**Comment by kprovance** [comment]
It cannot be disabled.  The entire point of having a JS button is so that javascript code will be executed when it's clicked.  If you're going to write your own code handler, then you can omit the script argument from your js_button option array, in which case the internal button click won't respond to anything, but again, if you want some action to be taken, you'll have to write your own button click handler.
