### ISSUE TITLE
color scheme list

### ISSUE THREAD

**Issue by OliverXie2016** [reduxframework/redux-extensions#306]
Hi Kevin,

Now i created two color scheme, how can i save the list instead of import them one by one on another new computer? what i mean is i'm going to create several color schemes which can let my end user to choose. is it possible?
 
![image](https://cloud.githubusercontent.com/assets/20784244/20339509/b0847bbc-ac17-11e6-8082-703a5fa2d2ef.png)

Regards
Oliver

**Comment by kprovance** [comment]
The extension inherently does not have any kind of first-run import feature.  I played with it once a long time ago and could never get it to work reliably, in that it would run once on install of the theme and then never run again.  A database key check was not reliable.  There were too many 'what ifs' that prevented it from working properly, so I gave up on it.  It would be easier to include a color scheme export file with your demo content and instruct the user to import it.

However, all that said, it's not impossible to code up your own solution, piggybacking the actual import feature.  it was I use in my own theme, with its demo content importer.

The way the manual import feature works is to take the uploaded import file and move it to the color scheme specific folder in the wp uploads folder and inside (<your_server_path>/wp-content/uploads/redux/color-schemes).  After a successful file move, the page then reloads and the color schemes extension checks for the existence of a properly formatted JSON file in that directory and does the import work.  However, it's a hard import, in that existing color scheme data is replace (another aspect I didn't feel like getting into, array comparison of existing data to preserve what was there).

So, with the demo content importer of my theme, I drop an exported color scheme file into that folder and let the code import it on next run.  With all this in mind, if you took a valid color scheme export and included it with your project, you could code up a solution to move the file into the folder I indicated above.  When the option panel loads, the file would be imported and your schemes would be listed.  But again, you'd lose existing data (which is bad if a client has their own schemes, they'd lose them, which is why perfecting the first-run logic is so important, the part I could never get right) and of course the logic to ensure such code would only run once on startup.  Believe me, if people lose their data because of such a feature, they WILL complain...and most folks don't back up their custom data in the event it might get lost.

That's about the only way to do what you want here.

**Comment by kprovance** [comment]
Thinking about it, there is another way to, but you'd have to be learned with javascript and AJAX.  You could use the JS Button extension (or a raw field if you're good with HTML), create a field above or beneath the color scheme field that would let the user to a one click import (and make sure you throw up an alert about overwriting existing data, even though no one seems to read such warnings).  Use javascript to capture that button click, post the file location to PHP via AJAX and do the file move to the specific color-scheme folder I described in my last reply, then reload the page.  That *should* work, although it's not tested.  IN theory it works the same as the manual import function without the upload of the file, but again, you'd have to code up your own JS and AJAX to do the file move.  If that's done successfully, a page reload will trigger the extension to do the import part.

**Comment by OliverXie2016** [comment]
The manual import function with demo importer is a good solution!  i will have a test on this.

Thanks Kevin!
