### ISSUE TITLE
Issue with Metabox And Theme Options 

### ISSUE THREAD

**Issue by manikbajaj** [reduxframework/redux-extensions#311]
Dear Support Team,

We are facing an issue, as we have our theme option with the name “NANO_OPTIONS” and we are using Redux meta box extensions as well. While using switch field type which may have a default value as “false,” but sometimes this false value overrides with the metal box value in the database. It means that the wp_options table where option_name is NANO_OPTIONS overrides with the value in the meta box.

I would appreciate if you could help me with this.

We have generated a support code and here it is for your reference: 

KnifbtauHKvkZld85K1BRSP9oqHOmPNvUQTsMjEh%2FZF66SIQvzOeIaA%2FFL9yCfAadQd
%2B7c4A9uMen8nb7OEca5KScSm1sTQMM7WrqvzFZj8jbLhhSV20vpNT%2BoV%2FaToO

Thanks

**Comment by kprovance** [comment]
If you have options in your metabox config that share IDs with optionsin your option panel, then you do not need to set the default for that field in the metaboxes, as the default from the option panel will be used.  It's been known to get in the way.  Since I don't know which field you are referring to, it's the only suggestion I have.  All I can tell you is - in my theme - all options in metaboxes that share IDs with the option panel, I set no default value to in metaboxes and everything works fine.  Also, make sure you have the latest metaboxes.  That info didn't show up in your support URL from some reason.  Oh, and upgrade Redux too.  You're behind several versions.
