### ISSUE TITLE
Billing issue #259 was not fixed

### ISSUE THREAD

**Issue by silviulucian** [reduxframework/redux-extensions#319]
https://github.com/reduxframework/redux-extensions/issues/259

This is the issue I'm talking about. Why did you close it if the subscription that I asked you to cancel was still active?

It just charged my CC again:

![screen shot 2017-02-07 at 22 15 11](https://cloud.githubusercontent.com/assets/235876/22709670/42eed6e4-ed83-11e6-8092-df82208a0177.png)

#2360 is the same #7408 which just happened now. There's still no discernible way for me to cancel this thing. This is the second year in a row I bring this up.

Please cancel this right now and refund me the amount it just charged me, otherwise I'll have to resort to filing a complaint with both Stripe and the bank to get a forced chargeback.

Thank you

**Comment by silviulucian** [comment]
@dovy @kprovance

**Comment by kprovance** [comment]
I don't have anything to do with the billing/money side of Redux.  That's all Dovy, and he's away till the weekend.  The reason I closed the ticket is because it was five months old and I was told it was being handled.  Byt he look of the screen shot, it appears the repeater subscription remains active, and why it was renewed.  I see other canceled items, but not one for the repater?  I don't know; I'm not allowed onto the side of the business.  When I see Dovy online, I'll point this out to him, but again, hes out of state on work related matters, so it might be a few days.  Sorry.

**Comment by silviulucian** [comment]
Thank you, appreciated!

**Comment by dovy** [comment]
@silviulucian So did you cancel the account or did it just close? Are you sure Stripe processed a charge properly? Please give me more details. I may have authorized a charge and blocked it because of insufficient funds. Thank you.

**Comment by dovy** [comment]
And please provide the project/product you used this in. ;)

**Comment by kprovance** [comment]
lol, you got lucky, @silviulucian .  Here he is!!

**Comment by silviulucian** [comment]
Shit, must have missed the notifications about your guys' reply here. Sorry about the delay... @dovy So, as I was saying in issue #259 last year, I wanted to cancel my subscription for the Repeater extension (the only one that was still active on my account) since I wasn't using it for anything. As I was saying then, I couldn't find any way of doing that (no billing email, no cancel link under my account, etc).

To answer your questions in order: I thought you were looking into it last year when we spoke and I didn't pay it no nevermind after that... I thought it was canceled since the issue I opened last year ended up being closed. And yeah, the charge was processed properly (I can send you a bank statement if you'd like... $115, again).

Also, I never used any of these in any product, client project etc. I just played around with them for fun (my dayjob is in advertising/mediabuying, I don't do WP professionally). Now, of course I don't have a problem with paying for them if I ever do end up needing them for anything but not the case now, just trying to cancel and get refunded for this last one.

**Comment by kprovance** [comment]
Did this get handled.  In two days I'm closing if there is no reply.

**Comment by silviulucian** [comment]
It did not get handled.

**Comment by craigpearson** [comment]
@silviulucian Did this ever get rectified? Our business is looking at buying the extensions bundle. But I'm hesitant to put this to the team if there's issues with cancellation / unauthorised payments

**Comment by silviulucian** [comment]
@craigpearson no, no it didn't, nobody here ever got back to me about canceling the subscription. Fortunately for me, my card expired and they couldn't bill it again.

**Comment by kprovance** [comment]
@craigpearson  - Unsubscribing from a purchase is as simple as going into your account, accessing the payment history tan and unsubscribing from a purchase.  Please be aware that once you have canceled, updated and support are no longer available.  We also expect one to maintain their subscription as long as they are using extensions in their products.  It's how support for Redux is shown and we may continue to exist, since the core is free.

If you have additional questions, please let me know.

Thanks.

**Comment by kprovance** [comment]
For the record, I am now in charge of all this...whereas I was not before.  All future issues can be sent directly to me.  Thanks.
