### ISSUE TITLE
Metaboxes + Woocommerce product

### ISSUE THREAD

**Issue by Ryu-k** [reduxframework/redux-extensions#334]
When calling the metaboxes in the product post type the "up-sells", "cross-sells", "grouped product" fields stop to work ( when you are editing a product : Product data > Linked product tab )

It seems that the problem is related to select2

http://support.redux.io/?id=psYziL2XCuXENA3bS0qnxmxRH1xYYJQ0JNjLALdxF%2FW%2F2JVbkWXsP0vQ1cMilDn6gqVHsWqWa4TsGN8LNjvKCw%3D%3D

Regards

**Comment by dovy** [comment]
Yes woocommerce updated their select2 without making a shim breaking code for any other plugins using an older select2. :(

**Comment by Ryu-k** [comment]
I see, any plan on updating the select2 plugin for the redux framework?
I would really like to be able to use the metaboxes in the products posts

Regards

**Comment by kprovance** [comment]
The next major version has the newer select2...and it took me DAYS to convert our code over to the new way select2 handles things.  Being asked to do it for the current version - because WC decided they don't want to shim out their changes, and FORCE everyone to update with them - really isn't fair, and IMO, unprofessional.  The next major version won't be ready for a while, which puts me in the unfortunate position of taking time away from my other work to put in two or more days of conversation and testing...for free.  We didn't break this, WC did, and they won;t take responsibility for their actions.  They like to break things with every update...with their users, with other developers, and they are big enough in which they do not have to care.  So, at this point in time, we don;t know what we are doing.  Recoding the 3.x version of select2 to be Redux prefixed will take way longer than conversation, and is also not feasible.  Maybe we can do a kick starter campaign?  A little bad press for WC might not be a bad thing.  Teach them a lesson.

**Comment by Ryu-k** [comment]
Hello Kevin,

Unfortunately I don't have money available at this moment, I am sorry to not be able to help.
I agree with you about WC updates, I hate the way they do it.
I don't know if we can do anything that will affect them, they would probably just ignore it.

Regards

**Comment by Ryu-k** [comment]
Hello,

Just wondering if there is any news, to not be able to use the metaboxes for woocommerce post is killing me.

Regards

**Comment by kprovance** [comment]
Right now, no.  Sorry.  If we had a super rich backer, maybe it coul d happen sooner.

**Comment by dovy** [comment]
We're hard at work on Redux 4.0, but this issue is they killed select2 for most everyone. Our solutions are: 1. Hack woo. 2. Prefix select2 to work in our system 3. Kill a woocommerce option.

I really just wish they would make it so they don't break code, but alas they don't seem to mind.  :(

**Comment by Ryu-k** [comment]
Yeah, what they did is really not cool, I really hate the way they update their plugin.

Just wanted to know if you were still working on this, unfortunately I don't have the money to back you up currently.

Thanks for your hard work.

Regards

**Comment by kprovance** [comment]
Okay, well, thanks for the well wishes.  I'm sure those will be helpful in some way.  Cheers.
