### ISSUE TITLE
✕ To allow data saving, make "..."/wp-content/uploads/redux/ writable.

### ISSUE THREAD

**Issue by blkgld** [reduxframework/redux-extensions#343]
Hello @dovy 

I tried to look for an answer to this issue here but I had no luck so I decided to message you.

I recently installed the Redux Framework to a new Wordpress site I am working on.

I found 2 error messages on the System Status Panel

**Status tab:**
Redux Data Directory Writable:	[?]	✕ To allow data saving, make "..."/wp-content/uploads/redux/ writable.

I checked the files indicated in the path but the redux folder is not even in the Uploads folder. I am at a lost with that.

**Change log:**
Parse error: syntax error, unexpected T_STATIC, expecting T_STRING or T_VARIABLE or '$' in "..."/wp-content/plugins/redux-framework/ReduxCore/inc/fields/raw/parsedown.php on line 1493

I contacted the theme developer yesterday to see if he could assist me but he could only tell me to contact my Hosting provider to have the Mod Security turned off. I managed to do that but that didn't fix the issue. I decided to contact you to see you if you can guide me in the right direction.

I have added some screencaps to my error messages.

Thanks
Christian

![screen shot 2017-06-19 at 4 10 08 pm](https://user-images.githubusercontent.com/16157298/27365199-9bbee470-55f3-11e7-8927-bb71928c2a7b.png)
![screen shot 2017-06-20 at 6 44 08 pm](https://user-images.githubusercontent.com/16157298/27365197-9bbd114a-55f3-11e7-98b4-9a1995ea8a13.png)
![screen shot 2017-06-20 at 6 44 30 pm](https://user-images.githubusercontent.com/16157298/27365198-9bbd6910-55f3-11e7-8965-6756f434b706.png)

**Comment by kprovance** [comment]
Please provide this information.  Also, please open the javascript console after you get that error and post back what it says there.

**Comment by blkgld** [comment]
Thank you for your response, @kprovance 

http://support.redux.io/?id=qkRJD2KOJ9Mh4hdWen9KckEWV3gsIzAqyT1oP%2FeoSCkp8m55tsqnyzDgtdOMoD4AoMjr2wi4ypAB0sifcoAS0w%3D%3D

I am not getting the error messages on the actual site, I am getting them in the Redux Framework Panel and on the Theme admin panel (royal theme by Athena). Where can I i get to the Javascript console to see that error from there?

**Comment by kprovance** [comment]
This is something your theme author should really be walking you through, since we typically do not support theme users, as we have no way of knowing how the theme uses our framework, plus, they get paid to support their product.  We do not.

As far as server setup, we cannot help with that, it falls outside the scope of any support we offer.

I looked at your data.  Part of the problem is the version of PHP you are using.  You have two options, 1) Contact your host and have them upgrade you to PHP 5.3 or higher, or 2) Download the version of Redux from our git to update the copy of Redux on your site, which fixes the issue with PHP 5.2 (https://github.com/reduxframework).  It will temporarily solve the problem, because the error is a direct result of PHP 5.2

**Comment by blkgld** [comment]
Thank you! I will take those steps now
