### ISSUE TITLE
Bug with theme hosted over Redux

### ISSUE THREAD

**Issue by tcareccio7** [reduxframework/redux-extensions#344]
I just paid $100 for Redux Support. There is a bug within my custom theme hosted over Redux... all words get overridden and I am not able to customize theme via Wordpress. Please advise

**Comment by kprovance** [comment]
Please contact me directly via email:  kevin@reduxframework.com  I may require sensitive information and would rather it not be posted for all to see.

Also, I need a more descriptive understanding of what is going on.  For example, Redux does not host anything.  It is a framework that allows developers to add options to their theme.  Are you the author of the theme, or are you customizing someone elses.  If it's the latter, are you using it as a child theme?  Any changes made directly to theme code will be lost when the author updates their theme.  Lastly, I don;pt understand what 'words get overridden' means, exactly, or 'customize through WordPress'  I may need to login to your Wordpress install to see, which is why the reply need to be done via email.

Thanks!
