### ISSUE TITLE
Metaboxes and compiler? [question]

### ISSUE THREAD

**Issue by CaptJiggly** [reduxframework/redux-extensions#346]
I'm working on a project that utilizes Redux and Metaboxes for per-page options, but my client wants to utilize the compiler as well, but after scanning through both sources, I'm not sure if that has been implemented.

Is it possible to trigger the Redux compiler per-page rather than site wide?

**Comment by kprovance** [comment]
Could you please post back your four digit order number, for verification please?  Thanks!

**Comment by CaptJiggly** [comment]
Is there any more information you need order wise?

**Comment by kprovance** [comment]
Sorry, the last time I checked this issue, Github said it was 404, so I assumed it was deleted.

Anyways, based on the original description, I'm not quite sure what you mean.  Any field with the compiler set to true (or with a class name attached to it, for the fields that support that) will trigger the compiler on save.A page save alone would not trigger the compiler.  That happens when Redux sees a field is set to field through it.  Since all the option's whether they are metabox box or global panel that have compiler set to true (or with a class name for those fields that support it) will be output by the compiler in one array.  There is no separation of global/per page.  Not without all kind of mods to the core.  That said, I did not author the original compiler code.  However, next time I speak with @dovy, I will ask him about that. (or maybe he'll chime in?  Hopefully?  ;) )

**Comment by CaptJiggly** [comment]
Yeah, I understand that part and it works fine outside of metabox, but if I change and save metabox options, compiler does not trigger, but during..normal usage I should say? The compiler hook is called.

I scanned through "meta_boxes_save" several times, but can't find anything that handles the compiler values during saving which makes me think its not possible without modding.

**Comment by kprovance** [comment]
The compiler is not handles through any metabox code...it's in the core, and it's not so simple to explain in one post.  I use metaboxes and compiler in my own theme.  It's always worked.  t this point, I can only guess it might be something in the config, or how the hook is setup?  I don't know.  None of that information was provided.

**Comment by CaptJiggly** [comment]
So since you've said the compiler is not handled through any metabox code, does that mean that metabox cannot compile any said options? My client wants each page to be able to have separate style sheets for per-page customization. There's nothing wrong with the hooks, compiler or metaboxes. They both work fine. My question is: When metaboxes are saved, it is possible for the compiler to well compile 
 the CSS values?

For example:
![ss1](https://user-images.githubusercontent.com/14947514/30676053-be3f3042-9e49-11e7-83a9-e33307f9b7f8.png)


Now, if I have the same exact setup in the metabox config (Which I have done), is it possible for the compiler to generate the CSS for said option?

My hook for core redux works fine:
![ss2](https://user-images.githubusercontent.com/14947514/30676058-ca028154-9e49-11e7-8c92-c5b95458a778.png)


But, with metaboxes: Nada.

That's my question if that cleared up anything for you.

**Comment by kprovance** [comment]
I've asked the author of metaboxes to review this and chime in.  I didn't write the extension, so I'm not sure where to look at this point.  Hopefully he'll be along soon.

**Comment by kprovance** [comment]
I have to ask from a dev perspective, how is this going to work per page?  Put aside the metabox issue for a moment.  Each page's metabox settings are designed to be unique, separate from one another.  If page (or post) metaboxes are saving to the same file via compile, how will each page or post differentiate from the other?  For example.  If page A has a background color of blue, and that writes to the css file you want to enqueue up from the saved location, and page B has a background color of red, and that writes to the same file...then all page backgrounds will be red, based on that saved file's CSS, yes?  Unless you plan to have separate css files per page, based on ID or the like, each page will overwrite all the settings in that file, and the CSS will not be unique per page, unless I've missed something.

If this is the case, the output feature is what you'd want to use because output is based on the front end loaded, and not saved options on the back/page/post  Plus, it works faster than the WP filesystem.

**Comment by CaptJiggly** [comment]
Originally, I was going to have separate files based on post ID, but it was requested to have them merged into one. I was not 100% sure on how to exactly pull that off, but main thing I need to see if per-page compile was even a thing, then I'd work from there.

**Comment by kprovance** [comment]
You'd have to add a page-id to each css selector and that file could get huge, fast.  I do this for a living, debug.  The output argument is suited to this kind of thing. Hopefully @Dovy can address this for you soon.

**Comment by CaptJiggly** [comment]
I'll know which direction to go on once I get some word on the topic. If not, I'll modify the source and add what's required for said project if its not possible with the current code when @dovy gets some time to respond.

**Comment by kprovance** [comment]
That's fine.  Your mods are your own.  We do not support Redux after mods are made...so if something breaks, please do not post about it.  I won't be able to help.  Even so, what you won;t to do - frankly - will not work.  You will spend weeks perfecting a system that is inherently flawed.  Good luck.
