### ISSUE TITLE
[Metaboxes] Metabox extension running too often

### ISSUE THREAD

**Issue by oliver-graetz** [reduxframework/redux-extensions#347]
In one of our projects, we created a metabox that does a `wp_remot_get` call to another WordPress installation to provide information about the posts on that other site. This call understandably is very expensive and takes some time. This should not be a problem because metaboxes are supposed to run only on the "post.php"and "post-new.php" pages.

But that was not the case. Both sites came to a grinding halt because they both started requesting information from each other even inside the API page under `/wp-json/wp/v2/`. We then started analyzing the problem and found this code in "extension-metaboxes.php" at line 70:

```php
    // Only run metaboxes on the pages/posts, not the front-end.
    // The DOING_AJAX check allows for redux_post_meta to work inside
    // AJAX calls. - kp
    if ( $pagenow !== "post-new.php" && $pagenow !== "post.php" ) {
        if ( is_admin() ) {
            if (defined('DOING_AJAX') && !DOING_AJAX) {
                return;
            }
            
            return;
        }
    }
```

I also found some information about this code here in issue #185 where the part about `DOING_AJAX` was added. But the whole logic inside the outer `if` seems wrong. The comment says "Only run metaboxes on the pages/posts, not the front-end" and then correctly checks if `$pagenow` is **not** related to those. But then it only stops running the extension if the current page is an admin page. This means the extension will run only on the "post.php" an "post-new.php" pages inside the admin area, but on top it will run everywhere in the frontend (even API calls), which doesn't make any sense. There should not be **any** condition inside the outer if. It should just always return.

If my understanding of this code is wrong then please change the comment in the code to correctly reflect when the code runs and why. Otherwise, please remove the `is_admin`.

Currently we are in preparation to implement workarounds for this performance hog in all our plugins using the metabox extension but it would be better if this could be solved here.

**Comment by kprovance** [comment]
As I recall this scenario:

```if ( $pagenow !== "post-new.php" && $pagenow !== "post.php" ) {```

This was supposed to weed out every other page on the backend but those two.  But for reasons I do not recall, that was not working, as is_admin() was added.  Now only those two pages would load the needed code.  The pblem was, redux_get_meta would fail in ajax routines triggered by ajax action hooks.  Since ajax-admin, or whatever the page is called is actually one of the pages blocked by is_admin(), a condition needed to be set to allow ajax called through while continue to ignore every other admin page out there.  So

```if ( defined( 'DOING_AJAX' ) && ! DOING_AJAX ) {```
Ajax might be present, but if its not actually running any ajax stuff, return, so nothing is run.  If no Ajax cost is set, the following return in the preview if/then prevent metaboxes from running.

This is not a condition n which removing is_admin() will fix anything.  If anything, it's break a lot of other things.  And metaboxes has code that must run on the front end, otherwise redux_post_meta will fail.

**Comment by oliver-graetz** [comment]
Okay, now I had the time to test this and your are right. The result of `redux_get_meta` in frontend pages is empty when commenting out the inner part of the `if()` construct. But there still is something wrong with the construct where another comment is better off in issue #185. I will comment there and then analyze here further.

**Comment by oliver-graetz** [comment]
Conclusion: Currently, I see no easy way to disable running the metaboxes in the frontend, but the comment above the if-construct should be changed to reflect the actual functionality. Also, as stated in issue #185, the code inside the outer if is currently not working correctly.

**Comment by Tofandel** [comment]
Actually there is, the logic is wrong indeed, to have the esired effect I believe you should just do this 
`if ( !is_admin()) {
		            return;
	            }
                if ( $pagenow !== "post-new.php" && $pagenow !== "post.php" && !(defined('DOING_AJAX') && DOING_AJAX) ) {
					return;
                }`
