### ISSUE TITLE
Metaboxes posts / custom posts typography field problem

### ISSUE THREAD

**Issue by Ryu-k** [reduxframework/redux-extensions#357]
I am currently using a metabox on pages / posts and custom posts.

The metabox only contains a "typography" field that let you choose the fonts for the page / posts menu.

The thing is that it is only working on page, if done for posts or custom posts it doesn't work.

On page the css file loaded in the header by the redux framework 
redux-google-fonts-youroptname-css
isn't updated for posts or custom posts, on pages it works fine

support url 
http://support.redux.io/?id=cMoP%2ByvfNkxbrakfcNhtNDCtj0K%2BZGF6or%2F0UgSIxn6rD1EkUNQ4%2BF0uNLfkYHCMY7M8OCvFgvST5jnKh3U1eg%3D%3D

redux version 3.6.8
metaboxes version 1.4.1

**Comment by Ryu-k** [comment]
Any news?

Regards

**Comment by dovy** [comment]
You cannot use a compiler output in metaboxes, there's no way for that to occur. You can do override on the pages, if you use the "output" arg with the proper CSS pointers. If you're writing to a flat file anywhere, that will always override anything set dynamically.

Best to make that NOT part of your compiler code and use output instead, or custom code some inline CSS based off the current page's value.

Best of luck.

**Comment by dovy** [comment]
p.s. Sorry for the delay. Been buried in a project.

**Comment by Ryu-k** [comment]
Hello Dovy, thanks for the reply.

I am not sure to understand, you mean the typography / font field metabox work in pages ( actually does, it add the custom google font to the css file that load google fonts "redux-google-fonts-youroptname-css" ) but will not work on custom posts?

The output part of my custom css work on both without any problem, its only the google fonts url not being updated ( it is updated if the metabox is used on a page though )

p.s no problem I understand how it is to been buried in a project. I also pinged you on slack of redux for a different matter, you really be awesome if you take a look when you have some time. Thanks in advance

**Comment by dovy** [comment]
@Ryu-k since it's just the CSS file that's the issue, the problem then is priority. Register you custom post type before init. I know the WP docs say to do init, but that's not required. Run it asap so Redux know it exists and can properly add the Font string.  :)

**Comment by kprovance** [comment]
I vaguely recall this being an issue with someone else.  If Redux and her extensions are being loaded too late, that is after init priority 10, funky things happen.  I tried to replicate it with my theme and could not...but in my theme, Redux loads before init 10 and all CPT load directly with the plugin that supports the theme...no init hook for that, as Dovy said.

**Comment by dovy** [comment]
Correct, now into the reason WHY. 

Unfortunately the init hook happens AFTER the header hook fires in WordPress. To account for this, Redux also runs before that. When Redux attempts to add the output code for google fonts or the output args, it searches for CPT's being used. Redux runs before init. Because you're delaying the load the font string never gets added.

Whew.

**Comment by Ryu-k** [comment]
Hello Dovy, Kevin

I see, so if I am loading my custom posts from a plugin it seems that I won't be able to have the google font css to be added, I will try to find an other way.

Thanks for the additional information!

Regards

**Comment by kprovance** [comment]
Why?  I do it on my theme.  I just use the init hook to fire register_taxonomy (or whatever the API is).  If it loads before init, it should work fine.

**Comment by Ryu-k** [comment]
I made a hook to init redux earlier but didn't worked, maybe I am missing something.

If you have time to share how you make your hook it would be appreciated.

Regards

**Comment by kprovance** [comment]
My theme got really complicated in terms of load order.  It became necessary because I wanted WooCommerce support, with metaboxes on the product pages.  As you may or may not know, Automattic keeps changing things in Woo and breaking backward compatibility with each update, so it seems.  They load their CPT on an init hook with priority 5, which makes life a kind of hell.  They now also have their product page loading as an archive page, which makes load order even more of a PITA.

IN my theme functions, I have a hook for after_theme_setup.  Most everything loads in there, including the option config for Redux.  

The second to last line is the Redux::setExtensions API call to load extensions

One of the things I have to do was add a line at the bottom of that config `Redux::init ();`

After that file has loaded, the next file I load is the file that sets the hook for metaboxes to load.

Now, jump ahead to the stupid plugin ThemeForest makes us do for CPT and shortcodes.  In there, on an init hook with priority 8, I load my CPT taxonomies (categories and tags) and then register the post type

The google fonts css loads on that CPT page (which you can see here, if you want:  http://www.requitedesigns.com/seele/portfolio/smoke-salt/  The css ID is 'redux-google-fonts-seele_options-css'

Anyways, that's what I ended up having to do...but it was out of making everything work with Woo.
