### ISSUE TITLE
Where is Redux Options Panel?

### ISSUE THREAD

**Issue by AirHunter007** [reduxframework/redux-extensions#369]
I have installed the plugin, connected it with functions file. Sample Options button appeared, but when I go to Sample Options, there is no menu on each option!
![screenshot_5](https://user-images.githubusercontent.com/40275729/43999006-087bcfd0-9e1c-11e8-9748-9df2d0762ed8.png)

**Comment by kprovance** [comment]
This is the issue tracker for Redux extensions.  Since this is core related, please post to this issue tracker:  https://github.com/reduxframework/redux-framework/issues

Also - and this is important - when you open the new issue window, there will be a block of text describing the information we REQUIRE.  Please do not skip over it. 

Thanks
