### ISSUE TITLE
Cannot input text into info fields

### ISSUE THREAD

**Issue by seamusdrumz** [ReduxFramework/redux-extensions#97]
My client recently purchased the WooThumbs - Multiple Images per Variation plugin from code canyon. Upon uploading the plugin to the theme I was alerted that I had to also load the Redux Framework to the theme in order for the WooThumbs plugin to work. The problem I am having is that when I visit the WooThumbs Settings page I cannot type any information within the boxes used to determine Slider Width and Ration.  I place my cursor within the field, click, and type... nothing.

I searched your forum for answers to my problem, and have not found anything that is relevant.

Can you help?

![multiple-images](https://cloud.githubusercontent.com/assets/8547577/4033128/67e5cb62-2c77-11e4-9829-a72a462dcb44.jpg)

**Comment by kprovance** [comment]
Also, Redux and Metaboxes have been updated since this issue, and lots of issues have been addressed.  Please upgrade both.  If the issue persists, please open a new ticket, making sure to supply the information specified here:  https://github.com/ReduxFramework/redux-framework/issues/1975.  Thanks!
